### ISSUE TITLE
MacOS issues

### ISSUE THREAD

**Issue by gabor7d2** [BME-MIT-IET/iet-hf-2024-macaroni#26]
I found some issues while playing on MacOS:

- [x] The game doesn't start properly in full screen, it starts as a borderless window but the macOS controls are still present and the game doesn't take the full screen. 

- [ ] The game sometimes freezes on startup.
- [x] The game throws this exception at startup: java.awt.FontFormatException: Unsupported sfnt ./assets/fonts/.DS_Store
  - this is due to macOS adding a .DS_Store file to directories to store metadata, this file should be excluded from loading.

**Comment by kereszthury** [comment]
Part of #25
